# Complete infra creation for selenium chrome/firefox and owasp security testing

version: '3'

services:
  firefox:
    image: selenium/node-firefox:4.0.0-alpha-5-20200515
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - hub
    environment:
      HUB_HOST: hub

  chrome:
    image: selenium/node-chrome:4.0.0-alpha-5-20200515
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - hub
    environment:
      HUB_HOST: hub

  hub:
    image: selenium/hub:4.0.0-alpha-5-20200515
    ports:
      - "4444:4444"

  zaproxy:
    image: owasp/zap2docker-stable:latest
    command: [
      #"zap.sh",
      "zap-x.sh",
      #"zap-webswing.sh",
      "-daemon",
      "-host", "0.0.0.0", "-port", "8082",
      "-config", "api.disablekey=true",
      "-config", "api.addrs.addr.name=.*",
      "-config", "api.addrs.addr.regex=true",
      "-config", "api.key=d025okl6n7blpkrr0iee6c7hsi",
      #"-addoninstall FOOXYZ",
      "-addonupdate"
    ]
    ports:
      - "127.0.0.1:8082:8082"