name: HybridTestFramework

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    container:
      image: dipjyotimetia/hybridtestframework:2.0

    steps:
    - uses: actions/checkout@v2
    - name: Install Google Chrome # Using shell script to install Google Chrome
      run: |
        chmod +x ./Driver/linux/InstallChrome.sh
         ./Driver/linux/InstallChrome.sh
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew # give permission to Gradle to run the commands
    - name: Build with Gradle
      run: ./gradlew task e2e
